module.exports = {
    purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    darkMode: false,
    theme: {
        fontFamily: {
            'mulish': ['Mulish', "sans-serif"],
            'playball': ['Playball', "cursive"],
        },
        extend: {
            backgroundColor: theme => ({
                ...theme("colors"),
                "primary": "#FFF14C",
                "primary-focus": "#343D4E",
                "secondary": "#377CFC",
                "secondary-focus": "#343D4E",
                "info": "#009585",
                "success": "#570df8",
                "warning": "#FF9A01",
                "error": "#FF5724",
                "base-100": "#ffffff",
                "base-200": "#F9FAFB",
                "base-250": "#F3F3F4",
                "base-300": "#d1d5db",
                "base-content": "#343D4E",
                "focus": "#343D4E",
            }),
            textColor: theme => ({
                ...theme("colors"),
                "primary": "#FFF14C",
                "primary-focus": "#343D4E",
                "secondary": "#377CFC",
                "secondary-focus": "#343D4E",
                "info": "#009585",
                "success": "#570df8",
                "warning": "#FF9A01",
                "error": "#FF5724",
                "focus": "#ffffff",
                "base-100": "#ffffff",
                "base-200": "#F9FAFB",
                "base-300": "#d1d5db",
                "base-600": "#00234B",
                "base-content": "#343D4E",
            }),
            borderColor: theme => ({
                ...theme("colors"),
                "primary": "#FFF14C",
                "primary-focus": "#343D4E",
                "secondary": "#377CFC",
                "secondary-focus": "#343D4E",
                "info": "#009585",
                "success": "#570df8",
                "warning": "#FF9A01",
                "error": "#FF5724",
                "base-100": "#ffffff",
                "base-200": "#F9FAFB",
                "base-300": "#d1d5db",
                "focus": "#343D4E",
            }),
            ringColor: theme => ({
                ...theme("colors"),
                "primary": "#FFF14C",
                "primary-focus": "#343D4E",
                "secondary": "#377CFC",
                "secondary-focus": "#343D4E",
                "info": "#009585",
                "success": "#570df8",
                "warning": "#FF9A01",
                "error": "#FF5724",
                "base-100": "#ffffff",
                "base-200": "#F9FAFB",
                "base-300": "#d1d5db",
                "focus": "#343D4E",
            }),
        },
    },
    variants: {
        extend: {
            borderStyle: ["hover"],
            fontsize: ["hover"],
        },
    },
    plugins: [
        require("@tailwindcss/line-clamp"),
        require("@tailwindcss/forms"),
    ],
}
