import {DropDownItem} from "./dropdown";

export const dataForInsurance: Array<DropDownItem> = [
    {name: "HMO", id: "HMO"},
    {name: "HMO", id: "HMO"},
    {name: "HMO", id: "HMO"},
    {name: "HMO", id: "HMO"},
    {name: "HMO", id: "HMO"},
]

export const dataForIllness: Array<{name: string, id: any}> = [
    {id: 1063, name: "Abdominal Pain"},
    {id: 1032, name: "Acid Reflux / Heartburn"},
    {id: 86, name: "Acne"},
    {id: 1246, name: "Alcoholism"},
    {id: 189, name: "Ankle Injuries / Sprain"},
    {id: 1712, name: "Ankle Pain"},
    {id: 422, name: "Ankle Problems"},
    {id: 2970, name: "Annual Check Up"},
    {id: 1717, name: "Arm Pain"},
    {id: 210, name: "Asthma"},
    {id: 1812, name: "Back Pain"},
    {id: 122, name: "Back Problems"},
    {id: 1045, name: "Bedwetting / Enuresis"},
    {id: 129, name: "Birth Control / Contraception"},
    {id: 1031, name: "Black Stool / Melena"},
    {id: 1916, name: "Bladder Pain / Interstitial Cystitis"},
    {id: 1071, name: "Bleeding"},
    {id: 1030, name: "Blood in Stool"},
    {id: 2162, name: "Breast Cancer Screening"},
    {id: 2649, name: "Breathing Problems"},
    {id: 390, name: "Bronchitis"},
    {id: 194, name: "Cardiovascular Screening Visit"},
    {id: 1090, name: "Carpal Tunnel Syndrome"},
    {id: 3210, name: "Chicken Pox"},
    {id: 201, name: "Cholesterol / Lipids Checkup"},
    {id: 3211, name: "Cold Sores / Herpes Labialis"},
    {id: 1462, name: "Concussion"},
    {id: 1600, name: "Constipation"},
    {id: 222, name: "Daytime Sleepiness"},
    {id: 1624, name: "Dehydration"},
    {id: 493, name: "Depression"},
    {id: 370, name: "Diabetes Consultation"},
    {id: 1332, name: "Diabetes Follow Up"},
    {id: 1070, name: "Diverticulitis / Diverticulosis"},
    {id: 468, name: "Dizziness"},
    {id: 3288, name: "Dry / Itchy Skin"},
    {id: 197, name: "ECG / EKG"},
    {id: 111, name: "Ear Infection"},
    {id: 463, name: "Ear Pain"},
    {id: 1492, name: "Ear Wax Cleaning"},
    {id: 166, name: "Eczema"},
    {id: 121, name: "Elbow Problems"},
    {id: 100, name: "Eye Infection"},
    {id: 1466, name: "Facial Pain"},
    {id: 1052, name: "Fainting / Syncope"},
    {id: 1695, name: "Fecal Incontinence"},
    {id: 3557, name: "Fertility Awareness / Natural Family Planning"},
    {id: 134, name: "Flu Shot"},
    {id: 187, name: "Foot Pain"},
    {id: 106, name: "Foot Problems"},
    {id: 1078, name: "Fracture"},
    {id: 1716, name: "Freezing of Warts"},
    {id: 2488, name: "Frequent Urination"},
    {id: 1253, name: "Frequent Urination"},
    {id: 1718, name: "Fungal Infection"},
    {id: 1719, name: "Gallstones"},
    {id: 2614, name: "Gastroesophageal Reflux Disease (GERD)"},
    {id: 83, name: "General Consultation"},
    {id: 1309, name: "General Follow Up"},
    {id: 3028, name: "HIV Pre-Exposure Prophylaxis (PrEP)"},
    {id: 90, name: "Hair Loss"},
    {id: 1093, name: "Hand Injury"},
    {id: 109, name: "Hand Problems"},
    {id: 499, name: "Headache"},
    {id: 114, name: "Hearing Problems"},
    {id: 1751, name: "Heavy or Irregular Vaginal Bleeding"},
    {id: 1072, name: "Hemorrhoids"},
    {id: 1204, name: "Herniated Disk"},
    {id: 208, name: "High Blood Pressure / Hypertension"},
    {id: 1761, name: "Hip Pain"},
    {id: 125, name: "Hip Problems"},
    {id: 113, name: "Hoarseness"},
    {id: 1040, name: "Incontinence"},
    {id: 371, name: "Infection Consultation"},
    {id: 1784, name: "Infertility Consultation"},
    {id: 1061, name: "Injury"},
    {id: 2452, name: "Injury/Minor Laceration"},
    {id: 1786, name: "Insect Bite(s)"},
    {id: 1294, name: "Irritable Bowel Syndrome"},
    {id: 1796, name: "Itching"},
    {id: 1801, name: "Joint Problem"},
    {id: 2811, name: "Joint Stiffness"},
    {id: 2705, name: "Knee Pain"},
    {id: 124, name: "Knee Problems"},
    {id: 1822, name: "Leg Pain"},
    {id: 1823, name: "Leg Problem"},
    {id: 3041, name: "Lump(s) in Breast"},
    {id: 172, name: "Medication Review"},
    {id: 482, name: "Menopause Consultation"},
    {id: 1367, name: "Menopause Follow Up"},
    {id: 226, name: "Migraine"},
    {id: 2529, name: "Mole Screening/Treatment"},
    {id: 1176, name: "Muscle Strain"},
    {id: 227, name: "Muscle Weakness / Palsy"},
    {id: 192, name: "Nail Abnormality"},
    {id: 1888, name: "Neck Pain"},
    {id: 1889, name: "Neck Problems"},
    {id: 2551, name: "New Patient Visit"},
    {id: 3656, name: "Nutrition Issues"},
    {id: 1915, name: "Obesity / Weight Loss Consultation"},
    {id: 1948, name: "Pain in Extremities"},
    {id: 1949, name: "Painful Menstruation / Dysmenorrhea"},
    {id: 5191, name: "Painful Sex / Dyspareunia"},
    {id: 87, name: "Palmoplantar Psoriasis"},
    {id: 2275, name: "Pelvic Pain"},
    {id: 2305, name: "Pre-Sports Physical"},
    {id: 509, name: "Pre-Surgery Checkup / Pre-Surgical Clearance"},
    {id: 77, name: "Prescription / Refill"},
    {id: 1456, name: "Prostate Cancer Screening"},
    {id: 3197, name: "Quitting Smoking / Smoking Cessation"},
    {id: 504, name: "Rash"},
    {id: 224, name: "Restless Legs Syndrome"},
    {id: 5190, name: "Ringing in Ears"},
    {id: 2350, name: "Sciatica"},
    {id: 2351, name: "Screening for Disease / Preventive Medicine"},
    {id: 132, name: "Sexual Dysfunction"},
    {id: 150, name: "Sexually Transmitted Disease (STD)"},
    {id: 2463, name: "Shingles"},
    {id: 2413, name: "Shoulder Pain"},
    {id: 161, name: "Shoulder Problem"},
    {id: 2366, name: "Skin Problem"},
    {id: 117, name: "Sleep Problems"},
    {id: 1489, name: "Sports Physical"},
    {id: 1029, name: "Stomach Pain"},
    {id: 3381, name: "Stomach Ulcer"},
    {id: 2657, name: "Swelling Joints/ Muscles"},
    {id: 119, name: "Swelling in Neck"},
    {id: 1094, name: "Tennis Elbow"},
    {id: 228, name: "Tingling / Numbness / Weakness"},
    {id: 1092, name: "Trigger Finger"},
    {id: 1536, name: "Type 1 Diabetes"},
    {id: 3038, name: "Type 2 Diabetes"},
    {id: 1545, name: "Urinary Incontinence"},
    {id: 1005, name: "Urinary Tract Infection (UTI)"},
    {id: 481, name: "Vaginal Discharge / Infection"},
    {id: 115, name: "Vertigo"},
    {id: 5189, name: "Voice Disorder"},
    {id: 191, name: "Wart(s)"},
    {id: 1060, name: "Weight Loss Consultation"},
    {id: 3196, name: "Weight Management"},
    {id: 2641, name: "Welcome to Medicare Physical"},
    {id: 1062, name: "Wound Care"},
    {id: 1091, name: "Wrist Pain"},
    {id: 421, name: "Wrist Problems"},
    {id: 2642, name: "Yearly Wellness Visit (For Medicare Patients)"},
]