import {DropDownItem} from "./dropdown";

export const dataForInsurance: Array<DropDownItem> = [
    {name: "1199SEIU", id: "1199SEIU"},
    {name: "1st Agency", id: "1st Agency"},
    {name: "20/20 Eyecare Plan", id: "20/20 Eyecare Plan"},
    {name: "AARP", id: "AARP"},
    {name: "ACE", id: "ACE"},
    {name: "AIG", id: "AIG"},
    {name: "APWU", id: "APWU"},
    {name: "ATRIO Health Plans", id: "ATRIO Health Plans"},
    {name: "AVMA Life", id: "AVMA Life"},
    {name: "Absolute Total Care", id: "Absolute Total Care"},
    {name: "Access Medicare (NY)", id: "Access Medicare (NY)"},
    {name: "Accountable Health Plan of Ohio", id: "Accountable Health Plan of Ohio"},
    {name: "Advanced Health", id: "Advanced Health"},
    {name: "AdvantageMD", id: "AdvantageMD"},
    {name: "Advantica", id: "Advantica"},
    {name: "Advent Health", id: "Advent Health"},
    {name: "Adventist Health", id: "Adventist Health"},
    {name: "Advocate Health Care", id: "Advocate Health Care"},
    {name: "Aetna", id: "Aetna"},
    {name: "Aetna Better Health", id: "Aetna Better Health"},
    {name: "Affinity Health Plan", id: "Affinity Health Plan"},
    {name: "AgeRight Advantage", id: "AgeRight Advantage"},
    {name: "AgeWell New York", id: "AgeWell New York"},
    {name: "Agile Health Insurance", id: "Agile Health Insurance"},
    {name: "Alameda Alliance for Health", id: "Alameda Alliance for Health"},
    {name: "Aliera Health Care", id: "Aliera Health Care"},
    {name: "Alignment Health Plan", id: "Alignment Health Plan"},
    {name: "All Savers Insurance", id: "All Savers Insurance"},
    {name: "AllCare Health", id: "AllCare Health"},
    {name: "AllState", id: "AllState"},
    {name: "AllWays Health Partners", id: "AllWays Health Partners"},
    {name: "Allegiance Life and Health", id: "Allegiance Life and Health"},
    {name: "Alliant Health Plans", id: "Alliant Health Plans"},
    {name: "Allianz Worldwide Care", id: "Allianz Worldwide Care"},
    {name: "Allwell", id: "Allwell"},
    {name: "AlohaCare", id: "AlohaCare"},
    {name: "AlphaCare", id: "AlphaCare"},
    {name: "AltaMed Senior BuenaCare (PACE)", id: "AltaMed Senior BuenaCare (PACE)"},
    {name: "Altius (Coventry Health Care)", id: "Altius (Coventry Health Care)"},
    {name: "AlwaysCare", id: "AlwaysCare"},
    {name: "Ambetter", id: "Ambetter"},
    {name: "AmeriGroup", id: "AmeriGroup"},
    {name: "AmeriHealth", id: "AmeriHealth"},
    {name: "AmeriHealth Caritas", id: "AmeriHealth Caritas"},
    {name: "America's 1st Choice", id: "America's 1st Choice"},
    {name: "American Behavioral", id: "American Behavioral"},
    {name: "American Eldercare", id: "American Eldercare"},
    {name: "American Healthcare Alliance", id: "American Healthcare Alliance"},
    {name: "American Maritime Officers Plans", id: "American Maritime Officers Plans"},
    {name: "American Republic Insurance Company", id: "American Republic Insurance Company"},
    {name: "Amida Care", id: "Amida Care"},
    {name: "Amplifon Hearing Health Care", id: "Amplifon Hearing Health Care"},
    {name: "Anthem Blue Cross", id: "Anthem Blue Cross"},
    {name: "Anthem Blue Cross Blue Shield", id: "Anthem Blue Cross Blue Shield"},
    {name: "Apostrophe", id: "Apostrophe"},
    {name: "ArchCare", id: "ArchCare"},
    {name: "Arise Health Plan", id: "Arise Health Plan"},
    {name: "Arizona Complete Health", id: "Arizona Complete Health"},
    {name: "Arizona Foundation for Medical Care", id: "Arizona Foundation for Medical Care"},
    {name: "Arkansas Blue Cross Blue Shield", id: "Arkansas Blue Cross Blue Shield"},
    {name: "Arkansas Total Care", id: "Arkansas Total Care"},
    {name: "Ascension Complete", id: "Ascension Complete"},
    {name: "Ascension Health", id: "Ascension Health"},
    {name: "Aspire Health Plan", id: "Aspire Health Plan"},
    {name: "Assurant Employee Benefits", id: "Assurant Employee Benefits"},
    {name: "Assurant Health", id: "Assurant Health"},
    {name: "Asuris Northwest Health", id: "Asuris Northwest Health"},
    {name: "Aultcare", id: "Aultcare"},
    {name: "AvMed", id: "AvMed"},
    {name: "Avera Health Plans", id: "Avera Health Plans"},
    {name: "Avesis", id: "Avesis"},
    {name: "BMC HealthNet Plan", id: "BMC HealthNet Plan"},
    {name: "Banker's Life", id: "Banker's Life"},
    {name: "Banner Health", id: "Banner Health"},
    {name: "Baptist Health Plan", id: "Baptist Health Plan"},
    {name: "BayCarePlus Medicare Advantage", id: "BayCarePlus Medicare Advantage"},
    {name: "Beacon Health Options", id: "Beacon Health Options"},
    {name: "Beaumont Employee Health Plan", id: "Beaumont Employee Health Plan"},
    {name: "Beech Street", id: "Beech Street"},
    {name: "Best Choice Plus", id: "Best Choice Plus"},
    {name: "Best Doctors Insurance", id: "Best Doctors Insurance"},
    {name: "Best Life And Health", id: "Best Life And Health"},
    {name: "Better Health (Florida Medicaid)", id: "Better Health (Florida Medicaid)"},
    {name: "Bind HealthCare", id: "Bind HealthCare"},
    {name: "Blue Choice Health Plan", id: "Blue Choice Health Plan"},
    {name: "Blue Cross Blue Shield (BCBS)", id: "Blue Cross Blue Shield (BCBS)"},
    {name: "Blue Cross Blue Shield Federal Employee Program", id: "Blue Cross Blue Shield Federal Employee Program"},
    {name: "Blue Cross Blue Shield of Alabama", id: "Blue Cross Blue Shield of Alabama"},
    {name: "Blue Cross Blue Shield of Arizona", id: "Blue Cross Blue Shield of Arizona"},
    {name: "Blue Cross Blue Shield of Georgia", id: "Blue Cross Blue Shield of Georgia"},
    {name: "Blue Cross Blue Shield of Illinois", id: "Blue Cross Blue Shield of Illinois"},
    {name: "Blue Cross Blue Shield of Kansas", id: "Blue Cross Blue Shield of Kansas"},
    {name: "Blue Cross Blue Shield of Kansas City", id: "Blue Cross Blue Shield of Kansas City"},
    {name: "Blue Cross Blue Shield of Louisiana", id: "Blue Cross Blue Shield of Louisiana"},
    {name: "Blue Cross Blue Shield of Massachusetts", id: "Blue Cross Blue Shield of Massachusetts"},
    {name: "Blue Cross Blue Shield of Michigan", id: "Blue Cross Blue Shield of Michigan"},
    {name: "Blue Cross Blue Shield of Minnesota", id: "Blue Cross Blue Shield of Minnesota"},
    {name: "Blue Cross Blue Shield of Mississippi", id: "Blue Cross Blue Shield of Mississippi"},
    {name: "Blue Cross Blue Shield of Montana", id: "Blue Cross Blue Shield of Montana"},
    {name: "Blue Cross Blue Shield of Nebraska", id: "Blue Cross Blue Shield of Nebraska"},
    {name: "Blue Cross Blue Shield of New Mexico", id: "Blue Cross Blue Shield of New Mexico"},
    {name: "Blue Cross Blue Shield of North Carolina", id: "Blue Cross Blue Shield of North Carolina"},
    {name: "Blue Cross Blue Shield of North Dakota", id: "Blue Cross Blue Shield of North Dakota"},
    {name: "Blue Cross Blue Shield of Oklahoma", id: "Blue Cross Blue Shield of Oklahoma"},
    {name: "Blue Cross Blue Shield of Rhode Island", id: "Blue Cross Blue Shield of Rhode Island"},
    {name: "Blue Cross Blue Shield of South Carolina", id: "Blue Cross Blue Shield of South Carolina"},
    {name: "Blue Cross Blue Shield of Tennessee", id: "Blue Cross Blue Shield of Tennessee"},
    {name: "Blue Cross Blue Shield of Texas", id: "Blue Cross Blue Shield of Texas"},
    {name: "Blue Cross Blue Shield of Vermont", id: "Blue Cross Blue Shield of Vermont"},
    {name: "Blue Cross Blue Shield of Western New York", id: "Blue Cross Blue Shield of Western New York"},
    {name: "Blue Cross Blue Shield of Wyoming", id: "Blue Cross Blue Shield of Wyoming"},
    {name: "Blue Cross of Idaho", id: "Blue Cross of Idaho"},
    {name: "Blue Cross of Northeastern Pennsylvania", id: "Blue Cross of Northeastern Pennsylvania"},
    {name: "Blue Shield of California", id: "Blue Shield of California"},
    {name: "Blue Shield of Northeastern New York", id: "Blue Shield of Northeastern New York"},
    {name: "Brand New Day", id: "Brand New Day"},
    {
        name: "Braven Health (Horizon Blue Cross Blue Shield of New Jersey)",
        id: "Braven Health (Horizon Blue Cross Blue Shield of New Jersey)",
    },
    {name: "BridgeSpan", id: "BridgeSpan"},
    {name: "Bridgeway Health Solutions", id: "Bridgeway Health Solutions"},
    {name: "Bright Health", id: "Bright Health"},
    {name: "Buckeye Health Plan", id: "Buckeye Health Plan"},
    {name: "CBA Blue", id: "CBA Blue"},
    {name: "CDPHP", id: "CDPHP"},
    {name: "CHAMPVA", id: "CHAMPVA"},
    {name: "CHP Group", id: "CHP Group"},
    {name: "CHRISTUS Health Plan", id: "CHRISTUS Health Plan"},
    {name: "CalOptima", id: "CalOptima"},
    {name: "CalPERS", id: "CalPERS"},
    {name: "CalViva Health", id: "CalViva Health"},
    {name: "California Foundation for Medical Care", id: "California Foundation for Medical Care"},
    {name: "California Health and Wellness", id: "California Health and Wellness"},
    {name: "Calvos", id: "Calvos"},
    {name: "Cambridge Health Alliance (CHA)", id: "Cambridge Health Alliance (CHA)"},
    {name: "Capital Blue Cross", id: "Capital Blue Cross"},
    {name: "Capital Health Plan", id: "Capital Health Plan"},
    {name: "Care Access Health Plan", id: "Care Access Health Plan"},
    {name: "Care Improvement Plus", id: "Care Improvement Plus"},
    {name: "Care N' Care", id: "Care N' Care"},
    {name: "Care1st", id: "Care1st"},
    {name: "CareConnect", id: "CareConnect"},
    {name: "CareFirst Blue Cross Blue Shield  (Health)", id: "CareFirst Blue Cross Blue Shield  (Health)"},
    {name: "CareMore", id: "CareMore"},
    {name: "CareOregon", id: "CareOregon"},
    {name: "CarePartners of Connecticut", id: "CarePartners of Connecticut"},
    {name: "CarePlus Health Plans (Florida Medicare)", id: "CarePlus Health Plans (Florida Medicare)"},
    {name: "CareSource", id: "CareSource"},
    {name: "Cascade Health Alliance", id: "Cascade Health Alliance"},
    {name: "Caterpillar", id: "Caterpillar"},
    {name: "CeltiCare Health Plan", id: "CeltiCare Health Plan"},
    {name: "CenCal Health", id: "CenCal Health"},
    {name: "Cenpatico", id: "Cenpatico"},
    {name: "Centennial Care", id: "Centennial Care"},
    {name: "Center for Elders' Independence (PACE)", id: "Center for Elders' Independence (PACE)"},
    {name: "CenterLight Healthcare", id: "CenterLight Healthcare"},
    {name: "Centers Plan for Healthy Living", id: "Centers Plan for Healthy Living"},
    {name: "Centers for Medicare & Medicaid Services", id: "Centers for Medicare & Medicaid Services"},
    {name: "Centivo", id: "Centivo"},
    {name: "Centra Health", id: "Centra Health"},
    {name: "Central California Alliance for Health", id: "Central California Alliance for Health"},
    {name: "Central Health Plan of California", id: "Central Health Plan of California"},
    {name: "Century Healthcare - CHC", id: "Century Healthcare - CHC"},
    {name: "Children's Community Health Plan", id: "Children's Community Health Plan"},
    {name: "Children's Medical Center Health Plan", id: "Children's Medical Center Health Plan"},
    {name: "Children's Medical Services (CMS)", id: "Children's Medical Services (CMS)"},
    {name: "Chinese Community Health Plan", id: "Chinese Community Health Plan"},
    {name: "Choice Care Network", id: "Choice Care Network"},
    {name: "Christian Healthcare Ministries", id: "Christian Healthcare Ministries"},
    {name: "Cigna", id: "Cigna"},
    {name: "Cigna-HealthSpring", id: "Cigna-HealthSpring"},
    {name: "Clarion Health", id: "Clarion Health"},
    {name: "Clark County Self-Funded Health", id: "Clark County Self-Funded Health"},
    {name: "Clear Spring Health", id: "Clear Spring Health"},
    {name: "Clements Worldwide", id: "Clements Worldwide"},
    {name: "Cleveland Clinic Employee Health Plan", id: "Cleveland Clinic Employee Health Plan"},
    {name: "Clover Health", id: "Clover Health"},
    {name: "Cofinity", id: "Cofinity"},
    {name: "Colorado Access", id: "Colorado Access"},
    {name: "Columbia Pacific CCO", id: "Columbia Pacific CCO"},
    {name: "Columbia United Providers", id: "Columbia United Providers"},
    {name: "ComPsych", id: "ComPsych"},
    {name: "Common Ground Healthcare Cooperative", id: "Common Ground Healthcare Cooperative"},
    {name: "Commonwealth Care Alliance", id: "Commonwealth Care Alliance"},
    {name: "Community Behavioral Health", id: "Community Behavioral Health"},
    {name: "Community Care Alliance of Illinois", id: "Community Care Alliance of Illinois"},
    {name: "Community Care Associates", id: "Community Care Associates"},
    {name: "Community Care Behavioral Health Organization", id: "Community Care Behavioral Health Organization"},
    {name: "Community Care Plan", id: "Community Care Plan"},
    {name: "Community Care of North Carolina", id: "Community Care of North Carolina"},
    {name: "Community Eye Care", id: "Community Eye Care"},
    {name: "Community First Health Plans", id: "Community First Health Plans"},
    {name: "Community Health Choice", id: "Community Health Choice"},
    {name: "Community Health Group", id: "Community Health Group"},
    {name: "Community Health Options", id: "Community Health Options"},
    {name: "Community Health Partners", id: "Community Health Partners"},
    {name: "Community Health Plan of Washington", id: "Community Health Plan of Washington"},
    {name: "CommunityCare of Oklahoma", id: "CommunityCare of Oklahoma"},
    {name: "CompBenefits", id: "CompBenefits"},
    {name: "Companion Life", id: "Companion Life"},
    {
        name: "Comprehensive Health Insurance Plan (CHIP) of Illinois",
        id: "Comprehensive Health Insurance Plan (CHIP) of Illinois",
    },
    {name: "Comprehensive Medical and Dental Program (CMDP)", id: "Comprehensive Medical and Dental Program (CMDP)"},
    {name: "Connect Care", id: "Connect Care"},
    {name: "ConnectiCare", id: "ConnectiCare"},
    {name: "Consolidated Health Plans", id: "Consolidated Health Plans"},
    {name: "Constitution Life", id: "Constitution Life"},
    {name: "Consumer Health Network", id: "Consumer Health Network"},
    {name: "Contra Costa Health Plan", id: "Contra Costa Health Plan"},
    {name: "Cook Children's Health Plan", id: "Cook Children's Health Plan"},
    {name: "Coordinated Care Health", id: "Coordinated Care Health"},
    {name: "Corvel", id: "Corvel"},
    {name: "CountyCare (Cook County)", id: "CountyCare (Cook County)"},
    {name: "Coventry Health Care", id: "Coventry Health Care"},
    {name: "Cox HealthPlans", id: "Cox HealthPlans"},
    {name: "Create", id: "Create"},
    {name: "Crystal Run Health Plans", id: "Crystal Run Health Plans"},
    {name: "Culinary Health Fund", id: "Culinary Health Fund"},
    {name: "CuraLinc Healthcare", id: "CuraLinc Healthcare"},
    {name: "DAKOTACARE", id: "DAKOTACARE"},
    {name: "DC Medicaid", id: "DC Medicaid"},
    {name: "DMC Care", id: "DMC Care"},
    {name: "DOCS (Doctors of the Oregon South Coast)", id: "DOCS (Doctors of the Oregon South Coast)"},
    {name: "DavidShield", id: "DavidShield"},
    {name: "Davis Vision", id: "Davis Vision"},
    {name: "Deaconess Health Plans", id: "Deaconess Health Plans"},
    {name: "Dean Health Plan", id: "Dean Health Plan"},
    {name: "Dell Children's Health Plan", id: "Dell Children's Health Plan"},
    {name: "Denver Health Medical Plan", id: "Denver Health Medical Plan"},
    {name: "Department of Medical Assistance Services", id: "Department of Medical Assistance Services"},
    {name: "Deseret Mutual", id: "Deseret Mutual"},
    {name: "Devon Health Services", id: "Devon Health Services"},
    {name: "Devoted Health", id: "Devoted Health"},
    {name: "Dimension Health", id: "Dimension Health"},
    {name: "Doctors HealthCare Plans", id: "Doctors HealthCare Plans"},
    {name: "Driscoll Health Plan", id: "Driscoll Health Plan"},
    {name: "EHP Significa", id: "EHP Significa"},
    {name: "EMI Health", id: "EMI Health"},
    {name: "ESSENCE Healthcare", id: "ESSENCE Healthcare"},
    {name: "Eastern Oregon Coordinated Care Organization", id: "Eastern Oregon Coordinated Care Organization"},
    {name: "Easy Choice Health Plan (California)", id: "Easy Choice Health Plan (California)"},
    {name: "Easy Choice Health Plan of New York", id: "Easy Choice Health Plan of New York"},
    {name: "El Paso First Health Plans", id: "El Paso First Health Plans"},
    {name: "Elderplan", id: "Elderplan"},
    {name: "EmblemHealth", id: "EmblemHealth"},
    {name: "EmblemHealth (formerly known as GHI)", id: "EmblemHealth (formerly known as GHI)"},
    {name: "EmblemHealth (formerly known as HIP)", id: "EmblemHealth (formerly known as HIP)"},
    {name: "Emory Health Care Plan", id: "Emory Health Care Plan"},
    {name: "Empire Blue Cross Blue Shield (Health)", id: "Empire Blue Cross Blue Shield (Health)"},
    {name: "Empire BlueCross BlueShield HealthPlus", id: "Empire BlueCross BlueShield HealthPlus"},
    {name: "Empire Plan", id: "Empire Plan"},
    {name: "Empower Healthcare Solutions", id: "Empower Healthcare Solutions"},
    {name: "Encore Health Network", id: "Encore Health Network"},
    {name: "Envolve Benefit Options", id: "Envolve Benefit Options"},
    {name: "Eon Health", id: "Eon Health"},
    {name: "Epic Hearing Health Care", id: "Epic Hearing Health Care"},
    {name: "Erickson Advantage", id: "Erickson Advantage"},
    {name: "EverCare", id: "EverCare"},
    {name: "Evergreen Health Cooperative", id: "Evergreen Health Cooperative"},
    {name: "Evolutions Healthcare Systems", id: "Evolutions Healthcare Systems"},
    {name: "Excellus Blue Cross Blue Shield", id: "Excellus Blue Cross Blue Shield"},
    {name: "Experience HealthND", id: "Experience HealthND"},
    {name: "Extended Managed Long Term Care", id: "Extended Managed Long Term Care"},
    {name: "EyeMed", id: "EyeMed"},
    {name: "Eyetopia Vision Care", id: "Eyetopia Vision Care"},
    {name: "Fallon Community Health Plan (FCHP)", id: "Fallon Community Health Plan (FCHP)"},
    {name: "Family Health Network", id: "Family Health Network"},
    {name: "FamilyCare Health Plans", id: "FamilyCare Health Plans"},
    {name: "Fidelis Care (NY)", id: "Fidelis Care (NY)"},
    {name: "First Choice Health", id: "First Choice Health"},
    {name: "First Choice Health Plan of Mississippi", id: "First Choice Health Plan of Mississippi"},
    {name: "First Health (Coventry Health Care)", id: "First Health (Coventry Health Care)"},
    {name: "FirstCare Health Plans", id: "FirstCare Health Plans"},
    {name: "FirstCarolinaCare", id: "FirstCarolinaCare"},
    {name: "Florida Blue: Blue Cross Blue Shield of Florida", id: "Florida Blue: Blue Cross Blue Shield of Florida"},
    {name: "Florida Community Care", id: "Florida Community Care"},
    {name: "Florida Health Care Plans", id: "Florida Health Care Plans"},
    {name: "Florida Health Partners", id: "Florida Health Partners"},
    {name: "Florida Hospital Healthcare System (FHHS)", id: "Florida Hospital Healthcare System (FHHS)"},
    {name: "Florida KidCare", id: "Florida KidCare"},
    {name: "Fort Bend County Indigent Health Care", id: "Fort Bend County Indigent Health Care"},
    {name: "Fortified Provider Network", id: "Fortified Provider Network"},
    {name: "Freedom Health", id: "Freedom Health"},
    {name: "Fresenius Health Plans", id: "Fresenius Health Plans"},
    {name: "Friday Health Plans", id: "Friday Health Plans"},
    {name: "GEHA", id: "GEHA"},
    {name: "GEMCare Health Plan", id: "GEMCare Health Plan"},
    {name: "GWH-Cigna (formerly Great West Healthcare)", id: "GWH-Cigna (formerly Great West Healthcare)"},
    {name: "Galaxy Health", id: "Galaxy Health"},
    {name: "Gateway Health", id: "Gateway Health"},
    {name: "Geisinger Health Plan", id: "Geisinger Health Plan"},
    {name: "General Vision Services (GVS)", id: "General Vision Services (GVS)"},
    {name: "GeoBlue", id: "GeoBlue"},
    {name: "Gilsbar 360 Alliance", id: "Gilsbar 360 Alliance"},
    {name: "Global Health", id: "Global Health"},
    {name: "Gold Coast Health Plan", id: "Gold Coast Health Plan"},
    {name: "Golden Rule", id: "Golden Rule"},
    {name: "Golden State Medicare Health Plan", id: "Golden State Medicare Health Plan"},
    {name: "Green Mountain Care (Vermont)", id: "Green Mountain Care (Vermont)"},
    {name: "Group Health Cooperative", id: "Group Health Cooperative"},
    {name: "Group Health Cooperative of Eau Claire", id: "Group Health Cooperative of Eau Claire"},
    {
        name: "Group Health Cooperative of South Central Wisconsin",
        id: "Group Health Cooperative of South Central Wisconsin",
    },
    {name: "Guardian", id: "Guardian"},
    {name: "Gundersen Health Plan", id: "Gundersen Health Plan"},
    {name: "HAP (Health Alliance Plan)", id: "HAP (Health Alliance Plan)"},
    {name: "HAP Midwest Health Plan", id: "HAP Midwest Health Plan"},
    {name: "HFN", id: "HFN"},
    {name: "HFS Medical Benefits", id: "HFS Medical Benefits"},
    {name: "HUSKY Health", id: "HUSKY Health"},
    {name: "Hamaspik Choice", id: "Hamaspik Choice"},
    {name: "Harken Health", id: "Harken Health"},
    {name: "Harmony Health Plan", id: "Harmony Health Plan"},
    {name: "Harvard Pilgrim Health Care", id: "Harvard Pilgrim Health Care"},
    {name: "Hawaii Medical Assurance Association (HMAA)", id: "Hawaii Medical Assurance Association (HMAA)"},
    {name: "Hawaii Medical Service Association (HMSA)", id: "Hawaii Medical Service Association (HMSA)"},
    {name: "Health Alliance", id: "Health Alliance"},
    {name: "Health Choice Arizona", id: "Health Choice Arizona"},
    {name: "Health First (FL)", id: "Health First (FL)"},
    {name: "Health First Colorado", id: "Health First Colorado"},
    {name: "Health First Health Plans (Florida)", id: "Health First Health Plans (Florida)"},
    {name: "Health Net", id: "Health Net"},
    {name: "Health New England", id: "Health New England"},
    {name: "Health Partners Plans (Pennsylvania)", id: "Health Partners Plans (Pennsylvania)"},
    {name: "Health Plan of Nevada", id: "Health Plan of Nevada"},
    {name: "Health Plan of San Joaquin", id: "Health Plan of San Joaquin"},
    {name: "Health Plan of San Mateo", id: "Health Plan of San Mateo"},
    {name: "Health Plus", id: "Health Plus"},
    {name: "Health Share of Oregon", id: "Health Share of Oregon"},
    {name: "Health Sun", id: "Health Sun"},
    {name: "HealthChoice Oklahoma", id: "HealthChoice Oklahoma"},
    {name: "HealthChoice of Michigan", id: "HealthChoice of Michigan"},
    {name: "HealthFirst (NY)", id: "HealthFirst (NY)"},
    {name: "HealthNow", id: "HealthNow"},
    {name: "HealthPartners", id: "HealthPartners"},
    {name: "HealthScope Benefits", id: "HealthScope Benefits"},
    {name: "HealthSmart", id: "HealthSmart"},
    {name: "HealthTeam Advantage", id: "HealthTeam Advantage"},
    {name: "Healthcare Highways Health Plan", id: "Healthcare Highways Health Plan"},
    {name: "Healthlink", id: "Healthlink"},
    {name: "Healthy Texas Women", id: "Healthy Texas Women"},
    {name: "HealthyCT", id: "HealthyCT"},
    {name: "Hear In America", id: "Hear In America"},
    {name: "Hennepin Health", id: "Hennepin Health"},
    {name: "Heritage Vision Plans", id: "Heritage Vision Plans"},
    {name: "Highmark Blue Cross Blue Shield", id: "Highmark Blue Cross Blue Shield"},
    {name: "Highmark Blue Cross Blue Shield of Delaware", id: "Highmark Blue Cross Blue Shield of Delaware"},
    {name: "Highmark Blue Shield", id: "Highmark Blue Shield"},
    {name: "Highmark BlueCross BlueShield of West Virginia", id: "Highmark BlueCross BlueShield of West Virginia"},
    {name: "Hillsborough Health Care Plan", id: "Hillsborough Health Care Plan"},
    {name: "Home State Health Plan", id: "Home State Health Plan"},
    {name: "Hometown Health", id: "Hometown Health"},
    {name: "Horizon Blue Cross Blue Shield of New Jersey", id: "Horizon Blue Cross Blue Shield of New Jersey"},
    {
        name: "Horizon Blue Cross Blue Shield of New Jersey For Barnabas Health",
        id: "Horizon Blue Cross Blue Shield of New Jersey For Barnabas Health",
    },
    {
        name: "Horizon Blue Cross Blue Shield of New Jersey For Novartis",
        id: "Horizon Blue Cross Blue Shield of New Jersey For Novartis",
    },
    {name: "Horizon NJ Health", id: "Horizon NJ Health"},
    {name: "Hudson Health Plan", id: "Hudson Health Plan"},
    {name: "Humana", id: "Humana"},
    {name: "Humana Behavioral Health (LifeSynch)", id: "Humana Behavioral Health (LifeSynch)"},
    {name: "IHC Health Solutions", id: "IHC Health Solutions"},
    {name: "IMS (Independent Medical Systems)", id: "IMS (Independent Medical Systems)"},
    {name: "IU Health Plans (Indiana University Health)", id: "IU Health Plans (Indiana University Health)"},
    {name: "Illinicare Health", id: "Illinicare Health"},
    {name: "Illinois' Primary Care Case Management (PCCM)", id: "Illinois' Primary Care Case Management (PCCM)"},
    {name: "Imagine Health", id: "Imagine Health"},
    {name: "Imperial Health Plan of California", id: "Imperial Health Plan of California"},
    {name: "Imperial Insurance Company of Texas", id: "Imperial Insurance Company of Texas"},
    {name: "Independence Blue Cross", id: "Independence Blue Cross"},
    {name: "Independence Care System", id: "Independence Care System"},
    {name: "Independent Health", id: "Independent Health"},
    {name: "Indiana Medicaid", id: "Indiana Medicaid"},
    {name: "Ingham Health Plan", id: "Ingham Health Plan"},
    {name: "Inland Empire Health Plan", id: "Inland Empire Health Plan"},
    {name: "Innovation Health", id: "Innovation Health"},
    {name: "Integra", id: "Integra"},
    {name: "Inter Valley Health Plan", id: "Inter Valley Health Plan"},
    {name: "InterCommunity Health Network CCO", id: "InterCommunity Health Network CCO"},
    {name: "Intergroup Services", id: "Intergroup Services"},
    {name: "Iowa MediPASS", id: "Iowa MediPASS"},
    {name: "Iowa Total Care", id: "Iowa Total Care"},
    {name: "Itasca Medical Care", id: "Itasca Medical Care"},
    {name: "Jackson Care Connect", id: "Jackson Care Connect"},
    {name: "Jackson Health Plan", id: "Jackson Health Plan"},
    {name: "Jai Medical Systems", id: "Jai Medical Systems"},
    {name: "Johns Hopkins Employer Health Programs", id: "Johns Hopkins Employer Health Programs"},
    {name: "KPS Health Plans", id: "KPS Health Plans"},
    {name: "Kaiser Permanente", id: "Kaiser Permanente"},
    {name: "Kansas HealthWave", id: "Kansas HealthWave"},
    {name: "Kansas Superior Select", id: "Kansas Superior Select"},
    {name: "KelseyCare Advantage", id: "KelseyCare Advantage"},
    {name: "Keystone First", id: "Keystone First"},
    {name: "L.A. Care Health Plan", id: "L.A. Care Health Plan"},
    {name: "L.A. Care Health Plan", id: "L.A. Care Health Plan"},
    {name: "Land of Lincoln Health", id: "Land of Lincoln Health"},
    {name: "Landmark Healthplan", id: "Landmark Healthplan"},
    {name: "Lasso Healthcare", id: "Lasso Healthcare"},
    {name: "Legacy Health", id: "Legacy Health"},
    {name: "Lehigh Valley Health Network Health Plan", id: "Lehigh Valley Health Network Health Plan"},
    {name: "Leon Medical Centers Health Plans", id: "Leon Medical Centers Health Plans"},
    {name: "Liberty Health Advantage", id: "Liberty Health Advantage"},
    {name: "Liberty HealthShare", id: "Liberty HealthShare"},
    {name: "Liberty Mutual", id: "Liberty Mutual"},
    {name: "LifeWise", id: "LifeWise"},
    {name: "Lifestyle Health", id: "Lifestyle Health"},
    {name: "Lighthouse Guild", id: "Lighthouse Guild"},
    {name: "Lighthouse Health Plan", id: "Lighthouse Health Plan"},
    {name: "Lincoln Financial Group", id: "Lincoln Financial Group"},
    {name: "Live360 Health Plan", id: "Live360 Health Plan"},
    {name: "Longevity Health Plan", id: "Longevity Health Plan"},
    {name: "Louisiana Healthcare Connections", id: "Louisiana Healthcare Connections"},
    {name: "Lutheran Preferred", id: "Lutheran Preferred"},
    {name: "MCM Maxcare", id: "MCM Maxcare"},
    {name: "MDwise", id: "MDwise"},
    {name: "MHNet Behavioral Health", id: "MHNet Behavioral Health"},
    {name: "MINES & Associates", id: "MINES & Associates"},
    {name: "MMM of Florida (Medicare and Much More)", id: "MMM of Florida (Medicare and Much More)"},
    {name: "MO HealthNet", id: "MO HealthNet"},
    {name: "MOAA (Miltary Officers Association of America)", id: "MOAA (Miltary Officers Association of America)"},
    {name: "MVP Health Care", id: "MVP Health Care"},
    {name: "Magellan Health", id: "Magellan Health"},
    {name: "MagnaCare", id: "MagnaCare"},
    {name: "Magnolia Health Plan", id: "Magnolia Health Plan"},
    {name: "Mail Handlers Benefit Plan", id: "Mail Handlers Benefit Plan"},
    {name: "MaineCare", id: "MaineCare"},
    {name: "Managed Health Network (MHN)", id: "Managed Health Network (MHN)"},
    {name: "Managed Health Services (Indiana)", id: "Managed Health Services (Indiana)"},
    {name: "Managed Health Services (Wisconsin)", id: "Managed Health Services (Wisconsin)"},
    {name: "Managed HealthCare Northwest", id: "Managed HealthCare Northwest"},
    {name: "March Vision Care", id: "March Vision Care"},
    {name: "Maricopa Health Plan", id: "Maricopa Health Plan"},
    {name: "Martin's Point HealthCare", id: "Martin's Point HealthCare"},
    {name: "Maryland Medical Assistance (Medicaid)", id: "Maryland Medical Assistance (Medicaid)"},
    {name: "Maryland Physicians Care", id: "Maryland Physicians Care"},
    {name: "MassHealth", id: "MassHealth"},
    {name: "Massachusetts Laborers' Health & Welfare Fund", id: "Massachusetts Laborers' Health & Welfare Fund"},
    {name: "Mayo Medical Plan", id: "Mayo Medical Plan"},
    {name: "McLaren Health Plan", id: "McLaren Health Plan"},
    {name: "MedStar Family Choice", id: "MedStar Family Choice"},
    {name: "MedStar Select", id: "MedStar Select"},
    {name: "Medi-Cal", id: "Medi-Cal"},
    {name: "MediGold", id: "MediGold"},
    {name: "MediPass", id: "MediPass"},
    {name: "Medica", id: "Medica"},
    {name: "Medica HealthCare Plans (Florida)", id: "Medica HealthCare Plans (Florida)"},
    {name: "Medicaid", id: "Medicaid"},
    {name: "Medical Eye Services (MES Vision)", id: "Medical Eye Services (MES Vision)"},
    {name: "Medical Mutual", id: "Medical Mutual"},
    {name: "Medicare", id: "Medicare"},
    {name: "Memorial Healthcare System", id: "Memorial Healthcare System"},
    {name: "Memorial Hermann", id: "Memorial Hermann"},
    {name: "Mercy Care", id: "Mercy Care"},
    {name: "Meridian Health Plan", id: "Meridian Health Plan"},
    {name: "Meritain Health", id: "Meritain Health"},
    {name: "MetLife", id: "MetLife"},
    {name: "MetroHealth", id: "MetroHealth"},
    {name: "MetroPlus Health Plan", id: "MetroPlus Health Plan"},
    {name: "Metropolitan Health Plan", id: "Metropolitan Health Plan"},
    {name: "Miami Children's Health Plan", id: "Miami Children's Health Plan"},
    {name: "Michigan Complete Health", id: "Michigan Complete Health"},
    {name: "Michigan No-Fault", id: "Michigan No-Fault"},
    {name: "Minuteman Health", id: "Minuteman Health"},
    {name: "Mississippi Division of Medicaid", id: "Mississippi Division of Medicaid"},
    {name: "Missouri Care", id: "Missouri Care"},
    {name: "Moda Health", id: "Moda Health"},
    {name: "Molina Healthcare", id: "Molina Healthcare"},
    {name: "Montana Health Cooperative", id: "Montana Health Cooperative"},
    {name: "Montefiore HMO", id: "Montefiore HMO"},
    {name: "MoreCare", id: "MoreCare"},
    {name: "Mountain Health Co-Op", id: "Mountain Health Co-Op"},
    {name: "Multiplan PHCS", id: "Multiplan PHCS"},
    {name: "Mutual of Omaha", id: "Mutual of Omaha"},
    {name: "NALC Health Benefit Plan", id: "NALC Health Benefit Plan"},
    {name: "NECA/IBEW Family Medical Care Plan", id: "NECA/IBEW Family Medical Care Plan"},
    {name: "NY State No-Fault", id: "NY State No-Fault"},
    {name: "NY: YourCare Health Plan", id: "NY: YourCare Health Plan"},
    {name: "National Congress of Employers (NCE)", id: "National Congress of Employers (NCE)"},
    {name: "National Vision Administrators", id: "National Vision Administrators"},
    {name: "Nationwide", id: "Nationwide"},
    {name: "Navajo Nation", id: "Navajo Nation"},
    {name: "Nebraska Total Care (Heritage Health)", id: "Nebraska Total Care (Heritage Health)"},
    {name: "Neighborhood Health Plan (Massachusetts)", id: "Neighborhood Health Plan (Massachusetts)"},
    {name: "Neighborhood Health Plan of Rhode Island", id: "Neighborhood Health Plan of Rhode Island"},
    {name: "Network Health Plan", id: "Network Health Plan"},
    {name: "Nevada Preferred", id: "Nevada Preferred"},
    {name: "New Directions Behavioral Health", id: "New Directions Behavioral Health"},
    {name: "New Hampshire Healthy Families", id: "New Hampshire Healthy Families"},
    {name: "New Mexico Health Connections", id: "New Mexico Health Connections"},
    {name: "New York Hotel Trades Council", id: "New York Hotel Trades Council"},
    {name: "NextLevelHealth", id: "NextLevelHealth"},
    {name: "Nippon Life Benefits", id: "Nippon Life Benefits"},
    {name: "North Carolina Health Choice (NCHC) for Children", id: "North Carolina Health Choice (NCHC) for Children"},
    {name: "North Shore LIJ CareConnect", id: "North Shore LIJ CareConnect"},
    {name: "Northland PACE", id: "Northland PACE"},
    {name: "NovaNet", id: "NovaNet"},
    {name: "OHMS (Oregon Health Management Services)", id: "OHMS (Oregon Health Management Services)"},
    {name: "OSU Health Plan", id: "OSU Health Plan"},
    {name: "Ohara, LLC", id: "Ohara, LLC"},
    {name: "Ohio Health Choice", id: "Ohio Health Choice"},
    {name: "OhioHealthy", id: "OhioHealthy"},
    {name: "On Lok Lifeways", id: "On Lok Lifeways"},
    {name: "On Lok Lifeways (PACE)", id: "On Lok Lifeways (PACE)"},
    {name: "OneNet PPO", id: "OneNet PPO"},
    {name: "Opticare of Utah", id: "Opticare of Utah"},
    {name: "Optima Health", id: "Optima Health"},
    {name: "Optimum HealthCare", id: "Optimum HealthCare"},
    {name: "Optum Health", id: "Optum Health"},
    {name: "Oscar Health Insurance Co.", id: "Oscar Health Insurance Co."},
    {name: "Oxford (UnitedHealthcare)", id: "Oxford (UnitedHealthcare)"},
    {name: "PA Health and Wellness", id: "PA Health and Wellness"},
    {name: "PA Medical Assistance", id: "PA Medical Assistance"},
    {name: "PBA (Patrolmen's Benefit Association)", id: "PBA (Patrolmen's Benefit Association)"},
    {name: "POMCO", id: "POMCO"},
    {name: "Pacific Health Alliance", id: "Pacific Health Alliance"},
    {name: "PacificSource Health Plans", id: "PacificSource Health Plans"},
    {name: "Palmetto GBA", id: "Palmetto GBA"},
    {name: "Pan-American Life Insurance Group", id: "Pan-American Life Insurance Group"},
    {name: "Paradigm Senior Care Advantage", id: "Paradigm Senior Care Advantage"},
    {name: "Paramount Healthcare", id: "Paramount Healthcare"},
    {name: "Parkland Community Health Plan", id: "Parkland Community Health Plan"},
    {name: "Parkview Total Health", id: "Parkview Total Health"},
    {name: "Partners Health Plan", id: "Partners Health Plan"},
    {name: "Partnership HealthPlan of California", id: "Partnership HealthPlan of California"},
    {name: "Passport Health Plan (Kentucky)", id: "Passport Health Plan (Kentucky)"},
    {name: "Passport To Health (Montana Medicaid)", id: "Passport To Health (Montana Medicaid)"},
    {name: "Patient 1st (Alabama Medicaid)", id: "Patient 1st (Alabama Medicaid)"},
    {name: "Peach State Health Plan", id: "Peach State Health Plan"},
    {name: "PeachCare for Kids", id: "PeachCare for Kids"},
    {name: "PennCare", id: "PennCare"},
    {name: "Peoples Health", id: "Peoples Health"},
    {name: "Phoenix Health Plan", id: "Phoenix Health Plan"},
    {name: "Physician Assured Access System", id: "Physician Assured Access System"},
    {name: "Physician Benefits Trust", id: "Physician Benefits Trust"},
    {name: "Physicians Eyecare Plan", id: "Physicians Eyecare Plan"},
    {name: "Physicians Health Plan", id: "Physicians Health Plan"},
    {name: "Physicians Health Plan of Northern Indiana, Inc.", id: "Physicians Health Plan of Northern Indiana, Inc."},
    {name: "PhysiciansCare", id: "PhysiciansCare"},
    {name: "Piedmont Community Health Plan", id: "Piedmont Community Health Plan"},
    {name: "Piedmont WellStar Health Plans", id: "Piedmont WellStar Health Plans"},
    {name: "Positive Health Care", id: "Positive Health Care"},
    {name: "Preferential Care Network", id: "Preferential Care Network"},
    {name: "Preferred Care Partners", id: "Preferred Care Partners"},
    {name: "PreferredOne", id: "PreferredOne"},
    {name: "Premera Blue Cross", id: "Premera Blue Cross"},
    {name: "Premier Health Plan", id: "Premier Health Plan"},
    {
        name: "Presbyterian Health Plan/Presbyterian Insurance Company",
        id: "Presbyterian Health Plan/Presbyterian Insurance Company",
    },
    {name: "Prestige Health Choice", id: "Prestige Health Choice"},
    {
        name: "Primary Care Case Management (North Dakota Medicaid)",
        id: "Primary Care Case Management (North Dakota Medicaid)",
    },
    {name: "Prime Health Services, Inc", id: "Prime Health Services, Inc"},
    {name: "Prime Healthcare", id: "Prime Healthcare"},
    {name: "PrimeWest Health", id: "PrimeWest Health"},
    {name: "Principal Financial Group", id: "Principal Financial Group"},
    {name: "Priority Health", id: "Priority Health"},
    {name: "Priority Partners", id: "Priority Partners"},
    {name: "ProCare Advantage", id: "ProCare Advantage"},
    {name: "Progressive", id: "Progressive"},
    {name: "Prominence Health Plan", id: "Prominence Health Plan"},
    {name: "ProviDRs Care (WPPA)", id: "ProviDRs Care (WPPA)"},
    {name: "Providence Health Plans", id: "Providence Health Plans"},
    {name: "Provider Partners Health Plan", id: "Provider Partners Health Plan"},
    {name: "Public Aid (Illinois Medicaid)", id: "Public Aid (Illinois Medicaid)"},
    {name: "Public Employees Health Program (PEHP)", id: "Public Employees Health Program (PEHP)"},
    {name: "Puget Sound Electrical Workers Trusts", id: "Puget Sound Electrical Workers Trusts"},
    {name: "QualCare", id: "QualCare"},
    {name: "QualChoice Arkansas", id: "QualChoice Arkansas"},
    {name: "Quality Health Plans of New York", id: "Quality Health Plans of New York"},
    {name: "Quartz", id: "Quartz"},
    {name: "Quest Behavioral Health", id: "Quest Behavioral Health"},
    {name: "Quiktrip", id: "Quiktrip"},
    {name: "RLI Indemnity Company", id: "RLI Indemnity Company"},
    {name: "Regence Blue Cross Blue Shield", id: "Regence Blue Cross Blue Shield"},
    {name: "Regence Blue Shield of Washington", id: "Regence Blue Shield of Washington"},
    {name: "Regent Insurance", id: "Regent Insurance"},
    {name: "Reliance Medicare Advantage", id: "Reliance Medicare Advantage"},
    {name: "Renaissance", id: "Renaissance"},
    {name: "Republic-Franklin Insurance", id: "Republic-Franklin Insurance"},
    {name: "RiverLink Health", id: "RiverLink Health"},
    {name: "RiverSpring Health Plans", id: "RiverSpring Health Plans"},
    {name: "RiverSpring at Home", id: "RiverSpring at Home"},
    {name: "Riverside Health", id: "Riverside Health"},
    {name: "Rockefeller Health Plan", id: "Rockefeller Health Plan"},
    {name: "Rocky Mountain Health Plans", id: "Rocky Mountain Health Plans"},
    {name: "SAG AFTRA Health Plan", id: "SAG AFTRA Health Plan"},
    {name: "SAMBA", id: "SAMBA"},
    {name: "SCAN Health Plan", id: "SCAN Health Plan"},
    {name: "SIHO Insurance Services", id: "SIHO Insurance Services"},
    {name: "SSM Health Care", id: "SSM Health Care"},
    {name: "Sagamore Health Network", id: "Sagamore Health Network"},
    {name: "Samaritan Health Plan Operations", id: "Samaritan Health Plan Operations"},
    {name: "San Francisco Health Plan", id: "San Francisco Health Plan"},
    {name: "Sana", id: "Sana"},
    {name: "Sanford Health Plan", id: "Sanford Health Plan"},
    {name: "Santa Clara Family Health Plan", id: "Santa Clara Family Health Plan"},
    {name: "Scott & White Health Plan", id: "Scott & White Health Plan"},
    {name: "Security Health Plan of Wisconsin, Inc.", id: "Security Health Plan of Wisconsin, Inc."},
    {name: "Select Care", id: "Select Care"},
    {name: "Select Health Network", id: "Select Health Network"},
    {name: "Select Health of South Carolina", id: "Select Health of South Carolina"},
    {name: "SelectHealth", id: "SelectHealth"},
    {name: "Sendero Health Plans", id: "Sendero Health Plans"},
    {name: "Seneca Insurance", id: "Seneca Insurance"},
    {name: "Senior Dimensions", id: "Senior Dimensions"},
    {name: "Senior Whole Health", id: "Senior Whole Health"},
    {name: "Sentry Insurance", id: "Sentry Insurance"},
    {name: "Seton Health Plan", id: "Seton Health Plan"},
    {name: "Sharp Health Plan", id: "Sharp Health Plan"},
    {name: "Sierra Health and Life", id: "Sierra Health and Life"},
    {name: "SightCare", id: "SightCare"},
    {name: "SilverSummit Healthplan", id: "SilverSummit Healthplan"},
    {name: "Simply Healthcare", id: "Simply Healthcare"},
    {name: "Simpra Advantage", id: "Simpra Advantage"},
    {name: "Solis Health Plans", id: "Solis Health Plans"},
    {name: "Solstice", id: "Solstice"},
    {name: "SoonerCare (Oklahoma Medicaid)", id: "SoonerCare (Oklahoma Medicaid)"},
    {name: "Soundpath Health", id: "Soundpath Health"},
    {name: "South Country Health Alliance", id: "South Country Health Alliance"},
    {name: "South Florida Community Care Network", id: "South Florida Community Care Network"},
    {name: "Southwestern Health Resources (SWHR)", id: "Southwestern Health Resources (SWHR)"},
    {name: "Spectera", id: "Spectera"},
    {name: "Standard Life and Accident Insurance Company", id: "Standard Life and Accident Insurance Company"},
    {name: "Stanford Health Care Advantage", id: "Stanford Health Care Advantage"},
    {name: "StarNet Insurance", id: "StarNet Insurance"},
    {name: "State Farm®", id: "State Farm®"},
    {name: "State National Insurance", id: "State National Insurance"},
    {name: "Staywell Insurance", id: "Staywell Insurance"},
    {
        name: "Steward Health Care Network - Health Choice Arizona",
        id: "Steward Health Care Network - Health Choice Arizona",
    },
    {name: "Steward Health Choice", id: "Steward Health Choice"},
    {name: "Stratose", id: "Stratose"},
    {name: "SummaCare", id: "SummaCare"},
    {name: "Summit Community Care", id: "Summit Community Care"},
    {name: "Sunflower Health Plan", id: "Sunflower Health Plan"},
    {name: "Sunrise Advantage Plan", id: "Sunrise Advantage Plan"},
    {name: "Sunshine Health", id: "Sunshine Health"},
    {name: "Superior HealthPlan", id: "Superior HealthPlan"},
    {name: "Superior Vision", id: "Superior Vision"},
    {name: "Sussex Insurance", id: "Sussex Insurance"},
    {name: "Sutter Health Plus", id: "Sutter Health Plus"},
    {name: "SutterSelect", id: "SutterSelect"},
    {name: "TNUS Insurance", id: "TNUS Insurance"},
    {name: "TakeCare", id: "TakeCare"},
    {name: "Teachers Health Trust", id: "Teachers Health Trust"},
    {name: "TexanPlus", id: "TexanPlus"},
    {name: "Texas Children's Health Plan", id: "Texas Children's Health Plan"},
    {name: "Texas Health Aetna", id: "Texas Health Aetna"},
    {name: "Texas Independence Health Plan (TIHP)", id: "Texas Independence Health Plan (TIHP)"},
    {name: "Texas Kids First", id: "Texas Kids First"},
    {name: "The HSC Health Care System", id: "The HSC Health Care System"},
    {name: "The Hartford", id: "The Hartford"},
    {name: "The Health Plan of the Upper Ohio Valley, Inc.", id: "The Health Plan of the Upper Ohio Valley, Inc."},
    {name: "Three Rivers Providers Network (TRPN)", id: "Three Rivers Providers Network (TRPN)"},
    {name: "Total Health Care", id: "Total Health Care"},
    {name: "Touchstone", id: "Touchstone"},
    {name: "Transamerica", id: "Transamerica"},
    {name: "Travelers", id: "Travelers"},
    {name: "Tricare", id: "Tricare"},
    {name: "Trillium Community Health Plan", id: "Trillium Community Health Plan"},
    {name: "Trilogy Health Insurance", id: "Trilogy Health Insurance"},
    {
        name: "Triple-S Salud: Blue Cross Blue Shield of Puerto Rico",
        id: "Triple-S Salud: Blue Cross Blue Shield of Puerto Rico",
    },
    {name: "Triwest Healthcare Alliance", id: "Triwest Healthcare Alliance"},
    {name: "TrueHealth New Mexico", id: "TrueHealth New Mexico"},
    {name: "Trusted Health Plan", id: "Trusted Health Plan"},
    {name: "Tuality Health Alliance", id: "Tuality Health Alliance"},
    {name: "Tufts Health Freedom Plan", id: "Tufts Health Freedom Plan"},
    {name: "Tufts Health Plan", id: "Tufts Health Plan"},
    {name: "UCHP (University of Chicago Health Plan)", id: "UCHP (University of Chicago Health Plan)"},
    {name: "UCare", id: "UCare"},
    {name: "UHA Health Insurance", id: "UHA Health Insurance"},
    {name: "ULLICO Casualty Company", id: "ULLICO Casualty Company"},
    {name: "UPMC Health Plan", id: "UPMC Health Plan"},
    {name: "US Family Health Plan", id: "US Family Health Plan"},
    {name: "US Health Group", id: "US Health Group"},
    {name: "USA Managed Care Organization", id: "USA Managed Care Organization"},
    {name: "USAble Mutual Insurance Company", id: "USAble Mutual Insurance Company"},
    {name: "Ultimate Health Plans", id: "Ultimate Health Plans"},
    {name: "Umpqua Health Alliance", id: "Umpqua Health Alliance"},
    {name: "UniCare", id: "UniCare"},
    {name: "Uniform Medical Plan", id: "Uniform Medical Plan"},
    {name: "Union Eye Care", id: "Union Eye Care"},
    {name: "Union Health Services, Inc", id: "Union Health Services, Inc"},
    {name: "Union Plans", id: "Union Plans"},
    {name: "United American", id: "United American"},
    {name: "United Behavioral Health", id: "United Behavioral Health"},
    {name: "UnitedHealthOne", id: "UnitedHealthOne"},
    {name: "UnitedHealthcare", id: "UnitedHealthcare"},
    {name: "UnitedHealthcare Community Plan", id: "UnitedHealthcare Community Plan"},
    {name: "UnitedHealthcare Oxford", id: "UnitedHealthcare Oxford"},
    {name: "Unity Health Insurance", id: "Unity Health Insurance"},
    {name: "Univera Healthcare", id: "Univera Healthcare"},
    {name: "Universal American", id: "Universal American"},
    {name: "Universal Underwriters Insurance", id: "Universal Underwriters Insurance"},
    {name: "University Hospitals (Health Design Plus)", id: "University Hospitals (Health Design Plus)"},
    {name: "University Physician Network (UPN)", id: "University Physician Network (UPN)"},
    {name: "University of Arizona Health Plans", id: "University of Arizona Health Plans"},
    {name: "University of Maryland Health Advantage", id: "University of Maryland Health Advantage"},
    {name: "University of Maryland Health Partners", id: "University of Maryland Health Partners"},
    {
        name: "University of St. Mary of the Lake - Mundelein Seminary",
        id: "University of St. Mary of the Lake - Mundelein Seminary",
    },
    {name: "University of Utah Health Plans", id: "University of Utah Health Plans"},
    {name: "Upper Peninsula Health Plan", id: "Upper Peninsula Health Plan"},
    {name: "VNS Choice Health Plans", id: "VNS Choice Health Plans"},
    {name: "VSP", id: "VSP"},
    {name: "Valley Forge Insurance", id: "Valley Forge Insurance"},
    {name: "Valley Health Plan", id: "Valley Health Plan"},
    {name: "Valor Health Plan", id: "Valor Health Plan"},
    {name: "Vantage Health Plan, Inc.", id: "Vantage Health Plan, Inc."},
    {name: "Ventura County Health Care Plan", id: "Ventura County Health Care Plan"},
    {name: "Vibra Health Plan", id: "Vibra Health Plan"},
    {name: "VillageCareMax", id: "VillageCareMax"},
    {name: "Virginia Coordinated Care (VCC)", id: "Virginia Coordinated Care (VCC)"},
    {name: "Virginia Health Network", id: "Virginia Health Network"},
    {name: "Virginia Premier Health Plan", id: "Virginia Premier Health Plan"},
    {name: "Vision Benefits of America", id: "Vision Benefits of America"},
    {name: "Vision Care Direct", id: "Vision Care Direct"},
    {name: "Vision Plan of America", id: "Vision Plan of America"},
    {name: "Viva Health Plan", id: "Viva Health Plan"},
    {name: "Vivida Health", id: "Vivida Health"},
    {name: "Volusia Health Network", id: "Volusia Health Network"},
    {name: "Vytra", id: "Vytra"},
    {name: "WEA Trust", id: "WEA Trust"},
    {name: "WPS Health Plan", id: "WPS Health Plan"},
    {name: "WRM America Indemnity Company", id: "WRM America Indemnity Company"},
    {name: "Well Sense Health Plan", id: "Well Sense Health Plan"},
    {name: "WellFirst Health", id: "WellFirst Health"},
    {name: "Wellcare", id: "Wellcare"},
    {name: "Wellmark Blue Cross Blue Shield", id: "Wellmark Blue Cross Blue Shield"},
    {name: "West American Insurance", id: "West American Insurance"},
    {name: "West Virginia Senior Advantage", id: "West Virginia Senior Advantage"},
    {name: "Western Health Advantage", id: "Western Health Advantage"},
    {name: "Western Sky Community Care", id: "Western Sky Community Care"},
    {name: "Willamette Valley Community Health", id: "Willamette Valley Community Health"},
    {name: "Workers' Compensation", id: "Workers' Compensation"},
    {name: "Yamhill Community Care Organization", id: "Yamhill Community Care Organization"},
    {name: "Zenith", id: "Zenith"},
    {name: "Zing Health", id: "Zing Health"},

]

export const dataForIllness: Array<{ name: string, id: any }> = [
    {id: 1063, name: "Abdominal Pain"},
    {id: 1032, name: "Acid Reflux / Heartburn"},
    {id: 86, name: "Acne"},
    {id: 1246, name: "Alcoholism"},
    {id: 189, name: "Ankle Injuries / Sprain"},
    {id: 1712, name: "Ankle Pain"},
    {id: 422, name: "Ankle Problems"},
    {id: 2970, name: "Annual Check Up"},
    {id: 1717, name: "Arm Pain"},
    {id: 210, name: "Asthma"},
    {id: 1812, name: "Back Pain"},
    {id: 122, name: "Back Problems"},
    {id: 1045, name: "Bedwetting / Enuresis"},
    {id: 129, name: "Birth Control / Contraception"},
    {id: 1031, name: "Black Stool / Melena"},
    {id: 1916, name: "Bladder Pain / Interstitial Cystitis"},
    {id: 1071, name: "Bleeding"},
    {id: 1030, name: "Blood in Stool"},
    {id: 2162, name: "Breast Cancer Screening"},
    {id: 2649, name: "Breathing Problems"},
    {id: 390, name: "Bronchitis"},
    {id: 194, name: "Cardiovascular Screening Visit"},
    {id: 1090, name: "Carpal Tunnel Syndrome"},
    {id: 3210, name: "Chicken Pox"},
    {id: 201, name: "Cholesterol / Lipids Checkup"},
    {id: 3211, name: "Cold Sores / Herpes Labialis"},
    {id: 1462, name: "Concussion"},
    {id: 1600, name: "Constipation"},
    {id: 222, name: "Daytime Sleepiness"},
    {id: 1624, name: "Dehydration"},
    {id: 493, name: "Depression"},
    {id: 370, name: "Diabetes Consultation"},
    {id: 1332, name: "Diabetes Follow Up"},
    {id: 1070, name: "Diverticulitis / Diverticulosis"},
    {id: 468, name: "Dizziness"},
    {id: 3288, name: "Dry / Itchy Skin"},
    {id: 197, name: "ECG / EKG"},
    {id: 111, name: "Ear Infection"},
    {id: 463, name: "Ear Pain"},
    {id: 1492, name: "Ear Wax Cleaning"},
    {id: 166, name: "Eczema"},
    {id: 121, name: "Elbow Problems"},
    {id: 100, name: "Eye Infection"},
    {id: 1466, name: "Facial Pain"},
    {id: 1052, name: "Fainting / Syncope"},
    {id: 1695, name: "Fecal Incontinence"},
    {id: 3557, name: "Fertility Awareness / Natural Family Planning"},
    {id: 134, name: "Flu Shot"},
    {id: 187, name: "Foot Pain"},
    {id: 106, name: "Foot Problems"},
    {id: 1078, name: "Fracture"},
    {id: 1716, name: "Freezing of Warts"},
    {id: 2488, name: "Frequent Urination"},
    {id: 1253, name: "Frequent Urination"},
    {id: 1718, name: "Fungal Infection"},
    {id: 1719, name: "Gallstones"},
    {id: 2614, name: "Gastroesophageal Reflux Disease (GERD)"},
    {id: 83, name: "General Consultation"},
    {id: 1309, name: "General Follow Up"},
    {id: 3028, name: "HIV Pre-Exposure Prophylaxis (PrEP)"},
    {id: 90, name: "Hair Loss"},
    {id: 1093, name: "Hand Injury"},
    {id: 109, name: "Hand Problems"},
    {id: 499, name: "Headache"},
    {id: 114, name: "Hearing Problems"},
    {id: 1751, name: "Heavy or Irregular Vaginal Bleeding"},
    {id: 1072, name: "Hemorrhoids"},
    {id: 1204, name: "Herniated Disk"},
    {id: 208, name: "High Blood Pressure / Hypertension"},
    {id: 1761, name: "Hip Pain"},
    {id: 125, name: "Hip Problems"},
    {id: 113, name: "Hoarseness"},
    {id: 1040, name: "Incontinence"},
    {id: 371, name: "Infection Consultation"},
    {id: 1784, name: "Infertility Consultation"},
    {id: 1061, name: "Injury"},
    {id: 2452, name: "Injury/Minor Laceration"},
    {id: 1786, name: "Insect Bite(s)"},
    {id: 1294, name: "Irritable Bowel Syndrome"},
    {id: 1796, name: "Itching"},
    {id: 1801, name: "Joint Problem"},
    {id: 2811, name: "Joint Stiffness"},
    {id: 2705, name: "Knee Pain"},
    {id: 124, name: "Knee Problems"},
    {id: 1822, name: "Leg Pain"},
    {id: 1823, name: "Leg Problem"},
    {id: 3041, name: "Lump(s) in Breast"},
    {id: 172, name: "Medication Review"},
    {id: 482, name: "Menopause Consultation"},
    {id: 1367, name: "Menopause Follow Up"},
    {id: 226, name: "Migraine"},
    {id: 2529, name: "Mole Screening/Treatment"},
    {id: 1176, name: "Muscle Strain"},
    {id: 227, name: "Muscle Weakness / Palsy"},
    {id: 192, name: "Nail Abnormality"},
    {id: 1888, name: "Neck Pain"},
    {id: 1889, name: "Neck Problems"},
    {id: 2551, name: "New Patient Visit"},
    {id: 3656, name: "Nutrition Issues"},
    {id: 1915, name: "Obesity / Weight Loss Consultation"},
    {id: 1948, name: "Pain in Extremities"},
    {id: 1949, name: "Painful Menstruation / Dysmenorrhea"},
    {id: 5191, name: "Painful Sex / Dyspareunia"},
    {id: 87, name: "Palmoplantar Psoriasis"},
    {id: 2275, name: "Pelvic Pain"},
    {id: 2305, name: "Pre-Sports Physical"},
    {id: 509, name: "Pre-Surgery Checkup / Pre-Surgical Clearance"},
    {id: 77, name: "Prescription / Refill"},
    {id: 1456, name: "Prostate Cancer Screening"},
    {id: 3197, name: "Quitting Smoking / Smoking Cessation"},
    {id: 504, name: "Rash"},
    {id: 224, name: "Restless Legs Syndrome"},
    {id: 5190, name: "Ringing in Ears"},
    {id: 2350, name: "Sciatica"},
    {id: 2351, name: "Screening for Disease / Preventive Medicine"},
    {id: 132, name: "Sexual Dysfunction"},
    {id: 150, name: "Sexually Transmitted Disease (STD)"},
    {id: 2463, name: "Shingles"},
    {id: 2413, name: "Shoulder Pain"},
    {id: 161, name: "Shoulder Problem"},
    {id: 2366, name: "Skin Problem"},
    {id: 117, name: "Sleep Problems"},
    {id: 1489, name: "Sports Physical"},
    {id: 1029, name: "Stomach Pain"},
    {id: 3381, name: "Stomach Ulcer"},
    {id: 2657, name: "Swelling Joints/ Muscles"},
    {id: 119, name: "Swelling in Neck"},
    {id: 1094, name: "Tennis Elbow"},
    {id: 228, name: "Tingling / Numbness / Weakness"},
    {id: 1092, name: "Trigger Finger"},
    {id: 1536, name: "Type 1 Diabetes"},
    {id: 3038, name: "Type 2 Diabetes"},
    {id: 1545, name: "Urinary Incontinence"},
    {id: 1005, name: "Urinary Tract Infection (UTI)"},
    {id: 481, name: "Vaginal Discharge / Infection"},
    {id: 115, name: "Vertigo"},
    {id: 5189, name: "Voice Disorder"},
    {id: 191, name: "Wart(s)"},
    {id: 1060, name: "Weight Loss Consultation"},
    {id: 3196, name: "Weight Management"},
    {id: 2641, name: "Welcome to Medicare Physical"},
    {id: 1062, name: "Wound Care"},
    {id: 1091, name: "Wrist Pain"},
    {id: 421, name: "Wrist Problems"},
    {id: 2642, name: "Yearly Wellness Visit (For Medicare Patients)"},
]
